# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

auth_service_account: &auth_service_account
  run:
    name: Login using service account
    command: |
      echo $GCLOUD_SERVICE_KEY | base64 --decode --ignore-garbage > ${HOME}/gcloud-service-key.json
      gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
      gcloud config set project $GCLOUD_PROJECT

deploy: &deploy
  run:
    name: Deploy
    command: |
      gcloud app deploy

jobs:
  build:
    docker:
      # specify the version you desire here
      - image: google/cloud-sdk:latest
      
    working_directory: ~/repo

    steps:
      - checkout
      - *auth_service_account
      - *deploy



